name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Hello world action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./action-a
      with:
        MY_NAME: "Babu"
