name: A workflow for my Hello world file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Hello world action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./action-a 
    - name: Build the Docker image
      run: docker build .